### ISSUE TITLE
How to import in AE

### ISSUE THREAD

**Issue by brunocannavina** [JuanIrache/gyrocam#2]
Hi greate job bro, I have a problem, I can't import to AE, it says: unsupported file type or extension!
Can you explain how to do that?

**Comment by JuanIrache** [comment]
Hi Bruno,

What version of After Effects are you using? on thing you can try is create an After Effects layer, set some keyframes to the position, copy those keyframes (just Control+C) and paste them into a text editor. Then see what the differences are between that format and the one Processing has exported. Maybe it's just a matter of specifying the version in the code, I'm not sure:

Let me know if it works or you need more help. Happy you're using the project :)

**Comment by brunocannavina** [comment]
Thanks Juan for your quickly answer! sorry for my english :D I'm from Argentina. I love processing and all your work is awesome! it's super easy! I'm using AE CS6 version 11.0 maybe that is the problem.

**Comment by JuanIrache** [comment]
Puedes crear unos keyframes de posición en AE, seleccionarlos, copiar y pegar aquí para ver el formato?

**Comment by brunocannavina** [comment]
Voy a tratar de instalar el AE CC 2018 creo que puede ser ese el problema, si no puedo, te vuelvo a consultar, pero de todas formas no quiero molestar. Desde ya sos muy amable por contestar y ayudar.

**Comment by JuanIrache** [comment]
No es molestia. Un saludo

**Comment by brunocannavina** [comment]
Hola Juan, con AE CC 2018 pude importar los .csv :D
ahora en lo que estoy teniendo problema es para relacionar la rotación y la posición del video con los .csv.
podrias pasarme los codigos para relacionarlos?

**Comment by JuanIrache** [comment]
Lo que yo hice es crear dos null objects sobre el vídeo, en uno pegué los datos de posición y en otro los de rotación. Linké (parent) el de posición al de rotación y el vídeo al de posición. Así: https://imgur.com/a/yPsw8iw

Cuando se mueve mucho uno de los ejes, hay que reajustar la rotación (quizás se pueda programar una solución automática, pero yo tuve que hacerlo manualmente). Así que puse unos sliders en los null objects para hacer esos ajustes.

A veces hay que mover el vídeo un fotograma adelante o atrás para que encaje con las vibraciones. También es muy importante haber configurado bien el sketch de Processing para que encaje con el formato del vídeo. Yo tuve que hacer muchísimas pruebas y errores.

Hablo de memoria, porque lo hice hace tiempo. Si recuerdo alguna cosa más te digo.

**Comment by brunocannavina** [comment]
Buenos dias Juan creo que ya casi lo tengo, nunca habia usado el after effects por eso se me complicó tanto.
Lo que hice fue lo siguiente: cree los dos null objects (uno de posición y otro de rotación) luego hice el parent tal cual mencionaste arriba. Lo que realmente no se como hacer es "pegar" los .cvs a cada null object.
![ae](https://user-images.githubusercontent.com/6666633/43358061-01d6ad1e-9262-11e8-8f63-8bbb23fb0a91.JPG)

Lo que si me dio resultado fue pasando los .csv a .txt y pegarlos ( Control + C/Control + V). Pero seguramente hay una forma mas facil.

**Comment by JuanIrache** [comment]
Ah, perdonam tendré que explicar eso en las instrucciones. Yo hago copiar y pegar desde el csv, (en excel o donde sea), selecciono todo el documento y contro+c.

Yo ponía los datos de posición en el Anchor Point del null object, no en Posición. No recuerdo el motivo. Puede que en Posición la compensación del movimiento to quede invertida?

**Comment by brunocannavina** [comment]
Me quedaba descentrada, voy a probar eso ;)
Fuiste de muchísima ayuda Juan! voy a seguir intentando hasta que quede realmente bien!
mi idea es hacer algo asi: 
https://www.youtube.com/watch?v=9LMMh1khIHY

Prometo si lo logro, realizar un tutorial explicando como usar tus herramientas así mas personas pueden usarlas.
Son todos los créditos tuyos :D muchísimas gracias.

**Comment by JuanIrache** [comment]
Gracias.

Sí, reproducir esas imágenes de kite surf es muy interesante. Recuerda que cuando la cámara cambie de dirección en los ejes x o y, tendrás que reajustar la rotación de z (no recuerdo si lo hacía en el null de rotación o de alguna otra forma, tendrás que experimentar).

Otras cosas que hice yo, que requieren bastante After Effects es compensar la óptica de ojo de pez y rellenar las esquinas (que al girar 360º la cámara serán visibles). Aquí hay algunas ideas para ello: https://youtu.be/37DBsYNXeEY

Si tuviese tiempo intentaría automatizar más el proceso, pero hay tantas cosas que hacer y aprender...

**Comment by brunocannavina** [comment]
Hola juan buen día, después de tanto tiempo volví a ponerme con este increíble proyecto, estuve mirando los nuevos cambios y me puse a leer todo el código de processing.
Tengo que agradecerte nuevamente y felicitarte. Lograste que me interese también el lenguaje Go. 
Tengo ganas de fusionar tanto los datos del giroscopio como los del acelerometro mediante un filtro complementario para poder estimar aun mejor el ángulo de rotación.
Mi duda es la siguiente:
Según el código, el ángulo de rotación se calcula sobre el eje Z
Y viendo la info que ofrece Gopro deberia ser eje Y.
![imu](https://user-images.githubusercontent.com/6666633/49089719-eba0a980-f23a-11e8-88bf-e82a8e2481c2.PNG)

**Comment by JuanIrache** [comment]
Hola Bruno,

Me alegro que te hayas animado a aprender Go. De hecho yo no sé mucho, solo lo que aprendí para modificar este proyecto. Tengo pendiente meterme más.

Hablo de memoria porque llevo un tiempo sin tocar a fondo el proyecto. Creo que el orden de los ejes cambia entre modelos de cámara y que las herramientas de extracción no tienen esos cambios en cuenta. Es decir, en los CSV el título de la columna no es necesariamente correcto. Habría que comprobarlo. Por otro lado, en Processing el eje Z sí es el de profundidad (y rotación 2D). Según la foto que enlazas el eje Y de GoPro corresponde al Z de Processing (y viceversa).

**Comment by brunocannavina** [comment]
Genial excelente! seguiré leyendo el codigo ;)

**Comment by brunocannavina** [comment]
Es correcto lo que decís, según el código y la documentación de Gopro esta perfecto para la Hero5 black (la cual tengo).
Pero si en otro caso uso una Hero6 o 7 funcionaria igual? (Ya que la disposición de los datos es distinta)

**Comment by JuanIrache** [comment]
Lo más fácil sería, en Processing, tener la opción de interpretar la Z del CSV como Y. Otra opción es, en Go, detectar qué cámara se está usando y renombrar las columnas del CSV
